### PR TITLE
change the copyright credits

### PR DESCRIPTION
**Pull request by nayuta-gondo**
"Nayuta, Inc." -> "Ptarmigan Project"
The copyright of this project belongs to all contributors,
not specific companies or organizations.

### CODE REVIEW

**Comment by kurihei** [comment]
Ack

**Comment by nayuta-gondo** [comment]
Dear contributors, please agree to change the copyright credit.
@nayuta-ueno @NayutaNakashima @nayuta-kohei @char1yxok @kurihei @tock203

**Comment by nayuta-gondo** [comment]
I agree.

**Comment by nayuta-kohei** [comment]
I agree.

**Comment by char1yxok** [comment]
I AGREE.

**Comment by nayuta-ueno** [comment]
ACK

**Comment by NayutaNakashima** [comment]
I agree.

**Comment by tock203** [comment]
I agree

**Comment by monaka** [comment]
I agree (note: I used to use monaka@hashhub.tokyo. )

**Comment by nayuta-gondo** [comment]
Thank you everyone.

**Pull request merged**
